### ISSUE TITLE
-v and -n arguments are not working in gemBS mapping

### ISSUE THREAD

**Issue by berguner** [heathsc/gemBS#10]
Hello,

When I use `-n` and `-v` parameters I get the error:
`ERROR: .../src/gemBSbinaries/gem-mapper: unrecognized option '--underconversion_sequence'`

Can you please check the issue?

Thanks,
Bekir

**Comment by MarcosFernandez** [comment]
Hi Bekir,

The arguments related to under and over conversion rate has been fixed. 

Thanks a lot for reporting this issue.

Cheers,
Marcos.

**Comment by berguner** [comment]
Thank you Marcos.
