### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'fileBam'

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#13]
https://github.com/heathsc/gemBS/blob/9b7d158bb7874a408bc290b6d1add74e7aa2e784/src/production.py#L574

Change that to:

```python
 raise CommandException("Sorry path %s was not found!!" %(fileBam)) 
```

**Comment by MarcosFernandez** [comment]
Hi IsmailM,

Thanks a lot for reporting this issue. It has been already fixed on the last github commit.

Cheers,
Marcos.
