### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#14]
https://github.com/heathsc/gemBS/blob/9b7d158bb7874a408bc290b6d1add74e7aa2e784/src/production.py#L406-L422

Error:
```
  File "...../python2.7/site-packages/src/production.py", line 421, in run
    for sample,listBams in self.samplesBams:
ValueError: too many values to unpack
```
`self.samplesBams` is a dict, so i'm guessing you need `iter_items()` on line 421:

```python
 for sample,listBams in self.samplesBams.iteritems(): 

```

**Comment by MarcosFernandez** [comment]
Hi IsmailM,

Thanks a lot for reporting this error. It has been already fixed in the last commit of GEMBS.

Cheers,
Marcos.
