### ISSUE TITLE
Use threads argument for Samtools

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#15]
E.g.

https://github.com/heathsc/gemBS/blob/9b7d158bb7874a408bc290b6d1add74e7aa2e784/src/__init__.py#L303

https://github.com/heathsc/gemBS/blob/9b7d158bb7874a408bc290b6d1add74e7aa2e784/src/__init__.py#L362

https://github.com/heathsc/gemBS/blob/9b7d158bb7874a408bc290b6d1add74e7aa2e784/src/__init__.py#L421

add `,"-@",threads,` in each case (but for the first one (L303), you might need to move [L318](https://github.com/heathsc/gemBS/blob/9b7d158bb7874a408bc290b6d1add74e7aa2e784/src/__init__.py#L318) further up to define threads)

**Comment by heathsc** [comment]
Thank you for your feedback.  Your suggestions have been incorporated in gemBS 3.0.0
