### ISSUE TITLE
gemBS merging-all - when there is only one input bam file

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#16]
In order to move from `gemBS mapping` to `gemBS bscall`, gemBS expects the bam filename to have changed from `flowcell_lane_index.bam` to `sample.bam`. 

The documentation does not make it clear that `gemBS merging-all` needs to be run even if there is only a single bam (in order to essentially rename files)

However, when there is only a single BAM file, the bam and index should simply be copied and not re-calculated?

https://github.com/heathsc/gemBS/blob/9b7d158bb7874a408bc290b6d1add74e7aa2e784/src/__init__.py#L400-L423

So with the above code:

- On L406, bam file is copied if there is only one file, which is great
- However, as shown on L421, the merged bam is always re-indexed (even if the bam file was copied and an index already has been previously computed),
   - hence, I would suggest the indexing should be moved into the if statement on L400, and the existing bam index should be copied and renamed when there is only a single bam file  ...

**Comment by MarcosFernandez** [comment]
Hi IsmailM,

Thanks a lot for reporting this idea. It has been applied to last GEMBS commit.

Cheers,
Marcos.
