### ISSUE TITLE
Skipping the first 5 bases in bscall

### ISSUE THREAD

**Issue by berguner** [heathsc/gemBS#17]
Hello,

The `-L` argument for bscall is set to 5 by default;
`parameters_bscall = ['%s' %(executables["bs_call"]),'-r',reference,'-L5','-n',sample,'--report-file',report_file]`

Does this mean the first (left) 5 bases of reads are neglected for bisulfite calling? We would like to use gemBS for RRBS analysis and first bases of the reads are critically important for RRBS. Can you make this an optional setting?

Best,
Bekir

**Comment by MarcosFernandez** [comment]
For RRBS data you should use --keep-duplicates in order to not merge reads that could be interpreted as duplicates.

You are right about -L argument, I will add it as soon as possible.

**Comment by MarcosFernandez** [comment]
Hi Bekir,

The last commit of GEMBS has already the options for trimming.
You can use:  `gemBS bscall --right-trim 0 --left-trim 0 --keep-duplicates`  for your RRBS data.

Cheers,
Marcos.

**Comment by berguner** [comment]
Thank you Marcos.

Cheers,
Bekir
