### ISSUE TITLE
Installation outside home directory

### ISSUE THREAD

**Issue by guillaumecharbonnier** [heathsc/gemBS#19]
Using  `python setup.py install --prefix=$MYPREFIX` I can install outside my home directory. But gemBS still look for some binaries at `~/.local/lib/python2.7/site-packages/src/gemBSbinaries` whereas it should look at `/$MYPREFIX/lib/python2.7/site-packages/src/gemBSbinaries`.

Is it possible to adjust gemBS behavior accordingly?

**Comment by heathsc** [comment]
Thank you for the feedback.  gemBS 3.0.0 should now handle this situation correctly.
