### ISSUE TITLE
getting several install errors 

### ISSUE THREAD

**Issue by christacaggiano** [heathsc/gemBS#2]
Hi, 

I was really enthusiastic about your new bioarvix paper! Upon installing I am getting several errors when I try to run python setup.py install --user. Most of these errors seem to be related to bs_call.c

s_call.c:284: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
bs_call.c:357: error: expected ‘)’ before ‘*’ token
bs_call.c:373: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
bs_call.c: In function ‘do_calling’:
bs_call.c:417: error: ‘gsl_integration_glfixed_table’ undeclared (first use in this function)
bs_call.c:417: error: (Each undeclared identifier is reported only once
bs_call.c:417: error: for each function it appears in.)
bs_call.c:417: error: ‘tab1’ undeclared (first use in this function)
bs_call.c:417: error: ‘tab2’ undeclared (first use in this function)
bs_call.c:417: warning: left-hand operand of comma expression has no effect
bs_call.c:420: warning: implicit declaration of function ‘get_gl_tab’
bs_call.c: In function ‘call_genotypes_ML’:
bs_call.c:1485: warning: array subscript has type ‘char’
bs_call.c:1433: warning: unused variable ‘fisher_p’
bs_call.c:1432: warning: unused variable ‘nr’

I am using python 2.6.6 as per the instructions. I think I have properly configured gsl-2.4 according to the gsl website instructions, however, I was unsure of the difference between include and lib so that could be a potential source of c related error. 

Any advice you would have here is greatly appreciated!

Thanks, 
Christa

**Comment by heathsc** [comment]
Thank you for the report.  We'll look into this and get back to you.

Simon

**Comment by MarcosFernandez** [comment]
Hi Christa,

Thanks a lot for your interest on gemBS. 
I guess your problem is that you have to fix the file Gsl.mk with the proper GSL paths.
This file is found at:

gemBS/tools/bs_call/

And you must modify two lines:
GSL_LIB = -L/yourGSLinstallation/lib/
GSL_INC = -I/yourGSLinstallation/include/

Once modified try to repeat the installation process.
