### ISSUE TITLE
Unique alignment rates in BScall and Mapping reports differ

### ISSUE THREAD

**Issue by berguner** [heathsc/gemBS#20]
Hello,

I realized the `Uniquely Aligned` values in the BSCall (variants) report and `Average Unique` values in the mapping report are different. Do these values represent different metrics?

Best,
Bekir

**Comment by heathsc** [comment]
Yes they are a little different.  The mapping report contains all sequences whereas the BSCall report only has information about the reads that were passed to BSCall (so no reads mapping to controls sequences or to contigs that are not called etc.)
