### ISSUE TITLE
Over/under conversion rates

### ISSUE THREAD

**Issue by berguner** [heathsc/gemBS#21]
Hello,

Can you please explain how over/under conversion rates are calculated?

Thanks,
Bekir

**Comment by heathsc** [comment]
In the reports?

**Comment by berguner** [comment]
Thanks to you I have found the explanation on documentation page.

I have run the pipeline on our data but over/under conversion rates seem incorrect. Under conversions rates are either 1 or 0 and over conversion rates are around -0.4. I don't understand how over conversion rate can be below zero and I think under conversion rates should be between 0-1. Please have a look at these IGV screen shots:

https://drive.google.com/file/d/1Uz8sIYJ-yFJapSxqH1ASwpqNqGcYcCum/view?usp=sharing
https://drive.google.com/file/d/1sJFXCwj-sWu70Hti4KUVydZtQUNUqrLy/view?usp=sharing

**Comment by heathsc** [comment]
Have the conversion control sequences been added to the index, and does gemBS have the names of the control sequences?  This process is explained better in the new version of the manual for gemBS 3.0.0.
