### ISSUE TITLE
nonbs_index disrupts example data processing

### ISSUE THREAD

**Issue by karl616** [heathsc/gemBS#23]
Hi,
I have problem running the example data. It fails at the index step with the error:

`KeyError: 'nonbs_index'`

I can bypass this by inserting `nonbs_index = False` in example.conf. Then, the BS-index is generated and I can continue with mapping. There is still a `FileNotFoundError` and the indexing does not generate a contig.sizes file and this stops me from continue to the calling step.

I have tried to stick to the guidelines, but maybe I'm missing something obvious. Anyhow, I would appreciate some help.

**Comment by karl616** [comment]
The problem seems to happen here:
https://github.com/heathsc/gemBS/blob/master/gemBS/production.py#L160
There are no default values for `nonbs_index` when populating the db. I mimicked how the dbsnp index handled... Not sure if it was worth a pull request :)

**Comment by heathsc** [comment]
Thanks for the report and the patch. I'll take a look.

Simon

**Comment by heathsc** [comment]
Merged proposed fix.  Issue closed.
