### ISSUE TITLE
Add to bioconda

### ISSUE THREAD

**Issue by karl616** [heathsc/gemBS#26]
Hi,
I want to add gemBS to bioconda.

Although I think it is nice how gemBS pulls down all software it needs during installation, my suggestion would be to allow conda to handle the dependencies. It is possible to fix the version of the dependencies. Most of the software is already available (samtools, htslib, wigToBigWig etc). Besides gem-mapper and bs_call, it is only bcftools that needs special treatment. This can be done.

In addition, compilation of external software needs to be optional. I have made an attempt here:
https://github.com/karl616/gemBS/blob/60de304e32c30bc81c62e5109fff1d71053e17a0/setup.py#L146-L181

I lift out building to build_ext and add a try/catch around _install_bundle. A setuptool option would be nicer.
Second is a new make target in the tools directory to compile repository internal software:
https://github.com/karl616/gemBS/blob/60de304e32c30bc81c62e5109fff1d71053e17a0/tools/Makefile#L49-L52

Software is installed into the bin folder of the conda installation/environment.

**What is needed from you is to make releases for gem-mapper and bs_call for each gemBS release.** (This would be the best solution for a bundled version as well.) For testing I make releases in my forks, but it would be nicer to point to the main repositories.

As I see it, there are pros and cons with this solution:
**pros:**
- Relies on bioconda for dependencies. Avoids multiple installations of the same software. (In my opinion, more in the conda mentality)
- Assigning versions to bs_call and gem-mapper makes the dependencies more transparent. Perhaps bring harmony between master and cnag versions.
- Successfully processes example data. (neutral)

**cons:**
- Updating bioconda requires up to four recipes to be updated simultaneously.
- potentially easier for users to overwrite software. A messed up path could also pose problems.
- Fringe cases. One example is libgen. It is included in the conda installation, but I'm not sure when this is needed during processing.

As mentioned I'm for separating the software. One installation for each software. But writing this I realize that reproducible processing is key here and that might be easier to guarantee with the bundled setup. I'm open for both solutions... What are your thoughts?

**Comment by heathsc** [comment]
This would have to be an option - for the standard install (outside of bioconda) I prefer that I can ensure that versions installed work correctly with the rest of gemBS.  I guess with bioconda you can also enforce the versions of the other programs that should be installed.

The GEM3 master, cnag and gembs branches are to allow specific modifications to GEM3 for processing at our centre (cnag) and for gembs that do not really belong in the standard vanilla version.  I may be able to merge master and gembs, but the cnag branch will remain separate.

I will add options to setup.py to allow different installations to be carried out.  If samtools, kent binaries, bs_call and gem3 are installed separately then it will be up to the user (or bioconda) to ensure that the user PATH and LD_LIBRARY_PATH are set correctly.  bcftools (and htslib) have to be installed with gemBS as the bcftools plugins have to be compiled with the source tree of the installed bcftools.

libgen is linked statically and does not need to be installed.

Simon

**Comment by karl616** [comment]
Yes, I agree, adding it to bioconda should add options to the user and not
remove them.

Personally, my current goal is to get gemBS into bioconda. I'm OK with
keeping the GEM3 branches split. I understand that this must be a developer
decision. If they stay split though, it would be practical to have a
gemBS/cnag release to refer to.

A separate installation option would be great. The way I did in my tests, I
added a custom bcftools version (compiled with mextr and snpxtr). Is htslib
needed outside bcftools?

Best,
Karl

**Comment by heathsc** [comment]
Hi Karl,

I have altered setup.py and tools/Makefile to make the make/install process more modular.  
setup.py now has the options:

--no-gem3
--no-samtools
--no-bscall
--no-kent

and as a convenience the option --minimal will turn on all of these, so only installing the base gemBS system + bcftools & plugins

If the --no-gem3 and --no-bscall options are used then the gem3-mapper and bs_call directories do not need to be present in tools/ (i.e., you can do git clone without the recursive option).

For gem3, you can install the release from the master branch.  The main difference (currently)  is that the master branch uses the 
-march-native optimization flag, which can cause problems with containers if the binaries are run on a machine with an older or less capable CPU then the compile machine.

Cheers,
Simon

**Comment by karl616** [comment]
Hi Simon,
after sorting out the gem3-mapper issues I'm back here again.

Would it be possible to tag a release of gemBS containing the latest changes? Most crucially the new setup procedure. At the moment I point the bioconda recipe to my own fork, but it would be nicer/more correct to point it directly here.

Best,
Karl

**Comment by karl616** [comment]
Thank you! I updated the recipe accordingly. I'll finalize the process on Monday and make sure to test it with the example data set.

**Comment by karl616** [comment]
It's done. There is a working version of gemBS in bioconda now. After setting up bioconda it can be installed with:
`conda install gembs`

I tested it on my own system and on a barebones image with the test example. Everything seems to work.

I'll close this issue.

**Comment by heathsc** [comment]
Thank you!
