### ISSUE TITLE
GemBS version

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#28]
I downloaded GemBS version 3.2.0 but `gemBS --version` says I have `3.0.0`

This is because the following two places say different things:

https://github.com/heathsc/gemBS/blob/80d12885e09bbfbfce37c4a5bcc13e819d6cf4c8/gemBS/commands.py#L13

https://github.com/heathsc/gemBS/blob/80d12885e09bbfbfce37c4a5bcc13e819d6cf4c8/setup.py#L19-L22

Would be nice if both of these say the same thing...

**Comment by heathsc** [comment]
Fixed - thank you for the report.

**Comment by IsmailM** [comment]
Hey, 

This is an issue again for the same reason.

As a result, I'm unable to distinguish what version of GemBS I have installed after upgrading. 

Perhaps it would make more sense to have the version defined in a separate file and import it in both files?

**Comment by heathsc** [comment]
Good point!

I will make the change

**Comment by heathsc** [comment]
This is done
