### ISSUE TITLE
IHEC_standard.conf `mode` is incorrect

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#29]
In the [documentation](http://statgen.cnag.cat/gemBS/UserGuide/_build/html/ihec_standards.html), for the IHEC_Standard.conf, `GemBS prepare` says:

```
 Warning: variable 'mode' in section [extract] not used
```

I think this is supposed to be: `strand_specific = True`

Can you update the docs with this.

**Comment by heathsc** [comment]
Fixed.  Thanks for the report.
