### ISSUE TITLE
Failed to compile bs_call

### ISSUE THREAD

**Issue by berguner** [heathsc/gemBS#3]
I failed installing gemBS because bs_call was failed to compile. I checked the tools/bs_call/src/Makefile.mk file and $CC environment variable was set to /usr/bin/gcc. This prevents using the newer gcc version which is loaded in the user's environment. Our system is pretty old and the version of /usr/bin/gcc is 3.4.0. I overcame this problem by editing tools/bs_call/src/Makefile.mk file and commenting out "CC=/usr/bin/gcc"

**Comment by MarcosFernandez** [comment]
Thanks a lot for your report. We will fix it on next release.

**Comment by berguner** [comment]
Hi Marcos,

I cloned the repository today for a clean install. This issue still exists. Changing it to `CC=$(which gcc)` solved the issue on my system.

Cheers,
Bekir

**Comment by MarcosFernandez** [comment]
Hi Bekir,

This issue has been fixed on the recently published version (GEMBS 2.0).
Thanks a lot  for your feedback.

Cheers,
Marcos.
