### ISSUE TITLE
GemBS output: Methylation estimate and base count columns 

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#36]
Hi,

We have had some issues in understanding the numbers in columns 7-11 of the GEMBS output and so would appreciate further explanation on the following columns:
- Methylation estimate (model based)
- Non-converted base count
- Converted base count
- Total bases supporting genotype call
- Total bases

Specifically:
- The sum of the non-converted and converted base counts do not always equal to number in the 'Total bases supporting genotype call' or 'Total bases’ columns. (i.e. it’s different in 95+% of the rows)
- Base counts can be quite different to that seen in IGV - even when taking into account the base quality, the read quality. Is there anything (like cysteine conversion over- or under-correction) that is also taken into account into this?

**Comment by heathsc** [comment]
Hi,

The number of total bases support ing genotype call is all reads (passing filters) that are not discordant with the genotype call.  The non-converted and converted base counts are the reads that are informative for methylation which is, on average, 50% of the total reads.  For top-strand cytosines, only reads that derive from the original top strand of the target DNA are informative for methylation.  Likewise for bottom-strand cytosines, only reads deriving from the original bottom strand are informative for methylation.

Base counts are simply counts after filtering, so the last column should be all reads covering the location after filtering.  

Points to remember:

(a) By default for CpG calls the counts on the top and bottom strands are summed.  If the strand-specific option to extract is used then the strand counts are given separately

(b) Filtering is performed on MAPQ, base quality, duplicate status and read pair orientation.  In addition by default the 5 bp at the beginning of each read are ignored for the calling.

(c) The methylation estimate is not simply the ratio of non-converted / (converted + non_converted) as it takes into account the conversion ratio, sequencing error etc.

Simon

**Comment by IsmailM** [comment]
It would be nice to have the above in the documentation (maybe in one of those "note" box)

**Comment by kellyliyichen** [comment]
Hi,

I have a follow-up on this issue.

If I use strand-specific methylation extraction, there should be two rows (from forward and reverse strands) for one CpG site. Does the last column mean the total bases for both strands? If so, to my understanding, it should be the sum of converted and non-converted bases in both strands. But in my output files, it is not always the case. Here are two examples:

E.g. 1
chr1    47361   47362   C       C       GQ=10;MQ=60     0.521   3       3       9       9
chr1    47362   47363   G       G       GQ=20;MQ=60     1.000   2       0       8       8

Should the total base (last column) be 8 (3+3+2+0)? But why it is 9 for the first row?

E.g. 2
chr1    51952   51953   C       C       GQ=71;MQ=59     1.000   15      0       25      25
chr1    51953   51954   G       G       GQ=69;MQ=59     0.947   9       1       27      27
Should the total base (last column) be 25 (15+0+9+1)? But why it is 27 for the second row?

Many thanks for your kind reply in advance!
