### ISSUE TITLE
TypeError: sequence item 15: expected str instance, NoneType found

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#37]
I see this error when trying to run `gemBS map`:

```
:
: Command map started at 2018-09-29 19:18:30.885616
:
: ------------ Mapping Parameters ------------
: Sample barcode   : pgp1
: Data set         : pgp01
: No. threads      : 16
: Index            : /data/pgp_data/pgp_wgbs/analysis/ref_indexes/hg38.BS.gem
: Paired           : True
: Read non stranded: False
: Type             : PAIRED
: Input Files      : /data/pgp_data/pgp_wgbs/analysis/fastq/pgp01_R1.fastq.gz,/data/pgp_data/pgp_wgbs/analysis/fastq/pgp01_R2.fastq.gz
: Output dir       : /data/pgp_data/pgp_wgbs/analysis/mapping/pgp1
:
: Bisulfite Mapping...
TypeError: sequence item 15: expected str instance, NoneType found
```

Looking at this at more details - this issue is raised at the following location (specifically at L165):

https://github.com/heathsc/gemBS/blob/87a6657ac1055311d9f429c8237329912cbca723/gemBS/utils.py#L161-L166

In my case, `self.command` is equal to the following:

```
>>> ['/usr/local/lib/python3.6/dist-packages/gemBS/gemBSbinaries/gem-mapper', '-I', '/data/pgp_data/pgp_wgbs/analysis/ref_indexes/hg38.BS.gem', '--i1', '/data/pgp_data/pgp_wgbs/analysis/fastq/pgp01_R1.fastq.gz', '--i2', '/data/pgp_data/pgp_wgbs/analysis/fastq/pgp01_R2.fastq.gz', '-p', '-t', '16', '--report-file', '/data/pgp_data/pgp_wgbs/analysis/mapping/pgp1/pgp01.json', '-r', '@RG\\tID:pgp01\\tSM:\\tBC:pgp1\\tPU:pgp01', '--underconversion_sequence', None, '--overconversion_sequence', None]
```

As such it seems the issue because the values of `--underconversion_sequence` and `--overconversion_sequence` is set to `None`.

Thus it seems that there should be a default value (of an empty string) set for both of these parameters (or rather they shouldn't be added to this list if their value is `None`)

**Comment by IsmailM** [comment]
Changing the below to check against `None` rather than an empty string (`""`) fixes the issue for me:


https://github.com/heathsc/gemBS/blob/71e7025117259d33d37c553214f5b30a14c12cd7/gemBS/__init__.py#L723-L727

**Comment by PoisonAlien** [comment]
Does this repo still maintained ? I have the same issue, and I am wondering if this has been addressed.

**Comment by heathsc** [comment]
Yes, it is maintained.  I will check this problem

Simon

**Comment by PoisonAlien** [comment]
Hi Simon,
Thanks for the reply. Here is the error log I have ..

```
: 
: Command map started at 2019-01-08 10:18:43.945975
: 
: ------------ Mapping Parameters ------------
: Sample barcode   : AS-277115-LR-38819
: Data set         : AS-277115-LR-38819
: No. threads      : 2
: Index            : /bigdisk/ref_db/mm10/gemBS/mm10.BS.gem
: Paired           : True
: Read non stranded: True
: Type             : PAIRED
: Input Files      : AS-277115-LR-38819_R1.fastq.gz,AS-277115-LR-38819_R2.fastq.gz
: Output dir       : /mapping/AS-277115-LR-38819
: 
: Bisulfite Mapping...
Traceback (most recent call last):
  File "/usr/local/bin/gemBS", line 11, in <module>
    load_entry_point('gemBS==3.2.2', 'console_scripts', 'gemBS')()
  File "/usr/local/lib/python3.5/dist-packages/gemBS/commands.py", line 157, in gemBS_main
    instances[args.command].run(args)
  File "/usr/local/lib/python3.5/dist-packages/gemBS/production.py", line 367, in run
    self.do_mapping(fl)
  File "/usr/local/lib/python3.5/dist-packages/gemBS/production.py", line 559, in do_mapping
    under_conversion=self.underconversion_sequence,over_conversion=self.overconversion_sequence) 
  File "/usr/local/lib/python3.5/dist-packages/gemBS/__init__.py", line 737, in mapping
    process = run_tools(tools, name="bisulfite-mapping", logfile=logfile)
  File "/usr/local/lib/python3.5/dist-packages/gemBS/utils.py", line 330, in run_tools
    p.start()
  File "/usr/local/lib/python3.5/dist-packages/gemBS/utils.py", line 237, in start
    logging.info("Starting:\n\t%s" % (self.to_bash_pipe()))
  File "/usr/local/lib/python3.5/dist-packages/gemBS/utils.py", line 276, in to_bash_pipe
    return " | ".join([p.to_bash() for p in self.processes])
  File "/usr/local/lib/python3.5/dist-packages/gemBS/utils.py", line 276, in <listcomp>
    return " | ".join([p.to_bash() for p in self.processes])
  File "/usr/local/lib/python3.5/dist-packages/gemBS/utils.py", line 165, in to_bash
    return " ".join(self.commands)
TypeError: sequence item 17: expected str instance, NoneType found
```

**Comment by heathsc** [comment]
I pushed a bug fix to github - can you check to see if this fixes your problem?

Thanks,
Simon

**Comment by PoisonAlien** [comment]
Hi Simon,
Thanks for the quick fix. Alignment went smoothly, however I have new error in BScall.. Below is the log..

```
: 
: Command call started at 2019-01-08 12:24:02.381098
: 
: ----------- Methylation Calling --------
: Reference       : /bigdisk/scJens/gem_bs/genome/mm10.fa
: Species         : mm10
: Right Trim      : 10
: Left Trim       : 10
: Chromosomes     : ['chr1', 'chr2', 'chrX', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr10', 'chr8', 'chr14', 'chr9', 'chr11', 'chr13', 'chr12', 'chr15', 'chr16', 'chr17', 'chrY', 'chr18', 'chr19', '@pool_1']
: Threads         : 6
: Sample: AS-277115-LR-38819    Bam: /bigdisk/scJens/gem_bs//mapping/AS-277115-LR-38819/AS-277115-LR-38819.bam
: 
: Methylation Calling...
2019-01-08 12:25:06,267 ERROR: Process '/home/epicwl/miniconda3/lib/python3.6/site-packages/gemBS/gemBSbinaries/bs_call' finished with 1
2019-01-08 12:25:06,267 ERROR: Loading reference sequences
2019-01-08 12:25:06,267 ERROR: Completed loading reference sequences
2019-01-08 12:25:06,267 ERROR: Processing chromosome chr2 (OK)
2019-01-08 12:25:06,267 ERROR: > System.Error::Signal raised (no=11)
Exception in thread Thread-2:
Traceback (most recent call last):
ValueError: Error while executing the bscall process.
```

And the above error just hangs, I had to terminate the process.

**Comment by heathsc** [comment]
OK, this is not good!  Anyway I can get access to the files so that I can try and reproduce the error on my system?

Simon

**Comment by PoisonAlien** [comment]
Do you need fastq files or the bam file ? 

Also this is a single cell library with non-directional protocol. I quickly did map-report and it says 33% overall alignment rate before deduplication (attached). For same sample when I used Bismark it reported ~18% alignment.

[AS-277115-LR-38819.html.zip](https://github.com/heathsc/gemBS/files/2736357/AS-277115-LR-38819.html.zip)


While you take a look at the error, could you suggest me if I can use any downstream tools deduplication (is picard fine?) and for methylation extraction ?

**Comment by heathsc** [comment]
Just the BAM should be fine.  Which reference are you using?  Normally deduplication is not required (it is performed by the caller).   If you could send a copy of the parameters files you are using for gemBS that would be helpful.

Thanks,

Simon

**Comment by heathsc** [comment]
OK, I have the files.  I’ll let you know how I get on with testing.

I have no experience with MethylDackel.  As far as I can see it does not take account of any possible sequence variation so the output should be treated with caution.  I’m not sure how well it will work with BAMs generated from gemBS - it depends whether it recognizes the tags in the BAM file that describe the bisulfite strand.  All bisulfite mappers use different tags for this (bs_call understands the BAMs from about 5 different mappers).

Simon

**Comment by PoisonAlien** [comment]
Ah! Got it. Thank you.

**Comment by PoisonAlien** [comment]
I followed the instructions as in the docs for installation. 

```
git clone --recursive https://github.com/heathsc/gemBS.git
python3 setup.py install
```
I do not have experience with docker/singularity but I see there are instructions in the docs. I will try it and let you know. 

Thank you for the help.

**Comment by heathsc** [comment]
Should be OK then - what type of computer are you running this on (CPU, memory, OS etc.) ?

Simon

**Comment by PoisonAlien** [comment]
I am running it on a local system with 128G RAM and 20 threads running on Ubuntu 16.04 LTS.
I just installed it on another system, will let you know if I face the same issuse..

**Comment by heathsc** [comment]
That should be more than enough and Ubuntu 16.04 is a tested system.  If you re-run the calling with less threads does it make a difference (it shouldn’t do, but I’m trying to pinpoint what could be triggering the bug).

Simon

**Comment by PoisonAlien** [comment]
Okay, I will check. Should I start with the alignment ? Or is there a way to use just 1 thread for `gemBS call`, since the config file has been set to 6 threads.

**Comment by heathsc** [comment]
Just the calling.  Maybe set it to 1 thread to see if it runs through.

Simon

**Comment by PoisonAlien** [comment]
Nope, still the same issue. I changed threads valueto 1 in `.gemBS/gemBS.json` and ran the command.

```
 gemBS call
: 
: Command call started at 2019-01-08 18:00:30.938804
: 
: ----------- Methylation Calling --------
: Reference       : /bigdisk/scJens/gem_bs/genome/mm10.fa
: Species         : mm10
: Right Trim      : 10
: Left Trim       : 10
: Chromosomes     : ['chr1', 'chr2', 'chrX', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr10', 'chr8', 'chr14', 'chr9', 'chr11', 'chr13', 'chr12', 'chr15', 'chr16', 'chr17', 'chrY', 'chr18', 'chr19', '@pool_1']
: Threads         : 1
: Sample: AS-277115-LR-38819    Bam: /bigdisk/scJens/gem_bs//mapping/AS-277115-LR-38819/AS-277115-LR-38819.bam
: 
: Methylation Calling...
2019-01-08 18:01:08,477 ERROR: Process '/home/epicwl/miniconda3/lib/python3.6/site-packages/gemBS/gemBSbinaries/bs_call' finished with 1
2019-01-08 18:01:08,478 ERROR: Loading reference sequences
2019-01-08 18:01:08,478 ERROR: Completed loading reference sequences
2019-01-08 18:01:08,478 ERROR: Processing chromosome chr7 (OK)
2019-01-08 18:01:08,478 ERROR: > System.Error::Signal raised (no=11)
Exception in thread Thread-2:
Traceback (most recent call last):
ValueError: Error while executing the bscall process.
```

**Comment by heathsc** [comment]
And this happens straightaway after the line 'Processing chromosome chr7 (OK)’ is printed?

Simon

**Comment by PoisonAlien** [comment]
Its weird. Every time I run `gemBS call` it stops at the next chromosome. 

```
: Methylation Calling...
2019-01-08 18:10:16,045 ERROR: Process '/home/epicwl/miniconda3/lib/python3.6/site-packages/gemBS/gemBSbinaries/bs_call' finished with 1
2019-01-08 18:10:16,045 ERROR: Loading reference sequences
2019-01-08 18:10:16,045 ERROR: Completed loading reference sequences
2019-01-08 18:10:16,045 ERROR: Processing chromosome chr10 (OK)
2019-01-08 18:10:16,046 ERROR: > System.Error::Signal raised (no=11)
Exception in thread Thread-1:
Traceback (most recent call last):
ValueError: Error while executing the bscall process.

2019-01-08 18:10:16,083 ERROR: Process '/home/epicwl/miniconda3/lib/python3.6/site-packages/gemBS/gemBSbinaries/bs_call' finished with 1
2019-01-08 18:10:16,083 ERROR: Loading reference sequences
2019-01-08 18:10:16,083 ERROR: Completed loading reference sequences
2019-01-08 18:10:16,083 ERROR: Processing chromosome chr8 (OK)
2019-01-08 18:10:16,083 ERROR: > System.Error::Signal raised (no=11)
Exception in thread Thread-2:
Traceback (most recent call last):
ValueError: Error while executing the bscall process.

: Methylation call done, samples performed: AS-277115-LR-38819

```

I also think its still using more than one thread. How do I force it to use single thread ?

**Comment by heathsc** [comment]
Is it completing the chromosomes each time?  If you look in the calling directory, do you see a bcf file and a json file for the chromosome (particularly the json file, as this is only generated at the end)?

**Comment by PoisonAlien** [comment]
Yes, there are json and bcf files for the ones that are completed. But all the json files are empty.

**Comment by PoisonAlien** [comment]
Okay, on a different system it works fine and calling completed without any error. I guess it was an installation problem on the main system. Thank you for your patient replies and apologies for the mess :| 
Should have checked it properly.

**Comment by heathsc** [comment]
Thanks for the feedback, but a segfault is never good and I would be happier knowing what caused it!  If you get around to re-installing gemBS on the original system, please let me know if it works (and definitely if it still does not work!).

Simon

**Comment by PoisonAlien** [comment]
Sure. Tomorrow I will check again and update you. Thanks again.

**Comment by PoisonAlien** [comment]
Hi, 
Simon, I reinstalled everything on the new system and it worked fine. Still dont know how it messed up the first installation. 

I have another question to ask. How do I run gemBS map with a custom input json file ?

```
$gemBS prepare -c ${conf} -t ${csv} --output ${sample_name}.json --no-db
$gemBS map 
gemBS.utils.CommandException: gemBS JSON file not found.
```
How do I pass output json from `prepare` command to map command ? 

Thanks again.

**Comment by heathsc** [comment]
To pass a custom json file, use the -j command line option *before* the subcommand so:

gemBS -j myfile.json map

Simon

**Comment by PoisonAlien** [comment]
Ah! Nice. It works. I was using the wrong way then `gemBS map -j myfile.json`

Thanks again.

**Comment by IsmailM** [comment]
Thanks for fixing this @heathsc 👍

**Comment by daisyko** [comment]
Has this bug been also fixed in the bioconda version of gemBS? I am using gemBS on bioconda and have encountered the same problem.

```
> : Command map started at 2019-01-31 10:32:53.303812
> : 
> : ------------ Mapping Parameters ------------
> : Sample barcode   : S014342
> : Data set         : sample1_1
> : No. threads      : 8
> : Index            : indexes/hg38.BS.gem
> : Paired           : True
> : Read non stranded: False
> : Type             : PAIRED
> : Input Files      : S014342_RDM04871_HLKK7CCXY_L2_1.fq.gz,S014342_RDM04871_HLKK7CCXY_L2_2.fq.gz
> : Output dir       : ./mapping/S014342
> : 
> : Bisulfite Mapping...
> Traceback (most recent call last):
>   File "/research/kevinyip11/ywgao/anaconda3/bin/gemBS", line 13, in <module>
>     load_entry_point('gemBS==3.2.0', 'console_scripts', 'gemBS')()
>   File "/research/kevinyip11/ywgao/anaconda3/lib/python3.6/site-packages/gemBS/commands.py", line 157, in gemBS_main
>     instances[args.command].run(args)
>   File "/research/kevinyip11/ywgao/anaconda3/lib/python3.6/site-packages/gemBS/production.py", line 366, in run
>     self.do_mapping(fl)
>   File "/research/kevinyip11/ywgao/anaconda3/lib/python3.6/site-packages/gemBS/production.py", line 558, in do_mapping
>     under_conversion=self.underconversion_sequence,over_conversion=self.overconversion_sequence) 
>   File "/research/kevinyip11/ywgao/anaconda3/lib/python3.6/site-packages/gemBS/__init__.py", line 726, in mapping
>     process = run_tools(tools, name="bisulfite-mapping", logfile=logfile)
>   File "/research/kevinyip11/ywgao/anaconda3/lib/python3.6/site-packages/gemBS/utils.py", line 330, in run_tools
>     p.start()
>   File "/research/kevinyip11/ywgao/anaconda3/lib/python3.6/site-packages/gemBS/utils.py", line 237, in start
>     logging.info("Starting:\n\t%s" % (self.to_bash_pipe()))
>   File "/research/kevinyip11/ywgao/anaconda3/lib/python3.6/site-packages/gemBS/utils.py", line 276, in to_bash_pipe
>     return " | ".join([p.to_bash() for p in self.processes])
>   File "/research/kevinyip11/ywgao/anaconda3/lib/python3.6/site-packages/gemBS/utils.py", line 276, in <listcomp>
>     return " | ".join([p.to_bash() for p in self.processes])
>   File "/research/kevinyip11/ywgao/anaconda3/lib/python3.6/site-packages/gemBS/utils.py", line 165, in to_bash
>     return " ".join(self.commands)
> TypeError: sequence item 15: expected str instance, NoneType found
```
