### ISSUE TITLE
gembs prepare command

### ISSUE THREAD

**Issue by christacaggiano** [heathsc/gemBS#41]
I have been running `gemBS prepare` for nearly a day, and it is not generating error messages, but it is also not doing or changing any files on my system.  It generated the following hidden directory almost immediately

```bash
393330691    4 drwxr-xr-x   3 christacaggiano lsd          4096 Dec 12 14:44 ./gembs_test
393330692    4 drwxr-xr-x   3 christacaggiano lsd          4096 Dec 12 14:23 ./gembs_test/.gemBS
393330693    4 drwxr-xr-x   2 christacaggiano lsd          4096 Dec 12 14:23 ./gembs_test/.gemBS/gemBS_inputs
393322921    4 -rw-r--r--   1 christacaggiano lsd           243 Dec 12 14:44 ./gembs_test/.gemBS/gemBS_inputs/metadata-1-8.csv
393322920    4 -rw-r--r--   1 christacaggiano lsd          1070 Dec 12 14:44 ./gembs_test/.gemBS/gemBS_inputs/1-8.conf
393322922    0 -rw-r--r--   1 christacaggiano lsd             0 Dec 12 14:23 ./gembs_test/.gemBS/gemBS.db
```

but no changes have been made since then. I am running it on a human sample, hg38 genome. I had a similar problem when I was running the worked example given in the documentation. Is this normal? Should this command take many hours to run?

**Comment by heathsc** [comment]
Dear Christa,

No, it should return pretty much immediately.  If you try running the prepare command with the --no-db option does it then return quickly?

Simon

**Comment by christacaggiano** [comment]
Hi, Adding that worked perfectly. Thanks!
