### ISSUE TITLE
no calling to be performed

### ISSUE THREAD

**Issue by PoisonAlien** [heathsc/gemBS#43]
Hi Simon,

I have this issue with gemBS call command, which fails to call or merge bcf files.

```
$gemBS -j AS-287569-LR-39945.json call --no-merge
: No calling to be performed
$gemBS -j AS-287569-LR-39945.json merge-bcfs -r
: No merging to be performed
```
It works again if I clear the output directory. Any way to force it.

**Comment by heathsc** [comment]
Are you using the  default or the no-db option?

Simon

**Comment by heathsc** [comment]
In this mode gemBS uses the contents of the output directories to check what has already been done so, as you said, to force it  to re-make the output files the old ones need to be removed.  We could add a forcing option, but since gemBS is intended to be operated in parallel I think that it is safest to require the user to explicitly remove the files rather than letting gemBS overwrite the older outputs.

Simon

**Comment by PoisonAlien** [comment]
Hi, 
I think it would be nicer to implement force calling and force extraction. I want to re-run extraction step with altered parameters but it wont perform extraction. Also I deleted some of the extraction files so that I can save space for new extraction results, but it fails to run again. It just shows below log and terminates..

```
: Methylation Extraction...
```

**Comment by PoisonAlien** [comment]
Hi Simon,
I am getting an error with reference to `map`. I few large samples (one complete lane for each sample) and the error is coming from samtools failing to create temporary files. I have attached the log output for your reference. Could you please suggest me if there is any workaround ? I can chop up my fastq files into smaller data-sets and try. 
[gemBS_map.log.txt](https://github.com/heathsc/gemBS/files/2758733/gemBS_map.log.txt)

**Comment by heathsc** [comment]
Could you be running out of space in the /tmp directory?  You could try using the -d option to gemBS map to set an alternate temporary file directory.

Simon

**Comment by PoisonAlien** [comment]
Got it. Will do it and let you know.
Also, for couple of samples I have error reports for `extract`.

```
: Command extract started at 2019-01-14 15:49:18.833186
: 
: Methylation Extraction...
2019-01-14 15:59:42,028 ERROR: Process '/home/mayakond/.conda/envs/gemBS/lib/python3.7/site-packages/gemBS/gemBSbinaries/bedToBigBed' finished with 255
2019-01-14 15:59:42,032 ERROR: pass1 - making usageList (22 chroms): 12443 millis
2019-01-14 15:59:42,033 ERROR: Error writing 6791 bytes: Operation not permitted
2019-01-14 15:59:42,033 ERROR: 
ValueError: Error while making bigBed files.
```

```
: Command extract started at 2019-01-14 16:38:01.801023
: 
: Methylation Extraction...
2019-01-14 16:50:13,562 ERROR: Process 'sed' finished with 4
2019-01-14 16:50:13,563 ERROR: sed: couldn't close stdout: Input/output error
ValueError: Error while uncompressing bed9+5 files.
```

**Comment by heathsc** [comment]
It looks like there is some problem with your filesystem - either too full or some other issue  These are not errors we see normally.

Simon

**Comment by PoisonAlien** [comment]
I think so too. These large drives are mounted remotely. I will try again on a local system.

**Comment by heathsc** [comment]
OK - it might be that under heavy load the network file system has some glitches.  Is this using NFS?

Simon

**Comment by PoisonAlien** [comment]
I believe so. My colleague knows more about it and he is on leave. I could ask him later.
