### ISSUE TITLE
updating the regex for finding files so it can find single-ended files

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#47]
Current Regex used for finding files is:

https://github.com/heathsc/gemBS/blob/fca06d59931a6639fee89839009847d84a08824a/gemBS/production.py#L471

At the moment, there needs to be at least one character between the `fli` and the file ending.

For example, in the case where 'sample1' is the `fli`:

`sample1.fastq.gz`  will not be matched
`sample1_.fastq.gz` will be matched
`sample1_R1.fastq.gz`  will be matched
`sample1_R2.fastq.gz`  will be matched

See https://regex101.com/r/1rIGRq/2/

I would vote for the removal of this requirement  - as single ended reads won't necessarily have anything after the `fli`

Suggested Fix:

```python
reg = re.compile("(.*){}(.*)[.](fastq|fq|fasta|fa|bam|sam)([.][^.]+)?$".format(fli, re.I))
# I removed a single `(.)` 
```

The above will match all the following
`sample1.fastq.gz`  
`sample1_.fastq.gz`
`sample1_R1.fastq.gz`  
`sample1_R2.fastq.gz`  

see https://regex101.com/r/Yj7yxl/1

Just a suggestion - feel free to close the issue, if there are other reasons for this.

**Comment by heathsc** [comment]
Change made.  Thanks.

**Comment by IsmailM** [comment]
Hi, 

Thank you for making this change.

Line 476 below also needs to be changed (as we have fewer groups in the regex) - it is now group 4 that we are looking at rather than group 5:

https://github.com/heathsc/gemBS/blob/0c4e7cb1820c08245902d432f79d4fd0c8e982c0/gemBS/production.py#L471-L477

At the moment, I see the following error:

```bash 
Traceback (most recent call last):
  File "/home/ucbtmog/.pyenv/versions/3.5.3/bin/gemBS", line 13, in <module>
    load_entry_point('gemBS==3.2.9', 'console_scripts', 'gemBS')()
  File "/home/ucbtmog/.pyenv/versions/3.5.3/lib/python3.5/site-packages/gemBS/commands.py", line 159, in gemBS_main
    instances[args.command].run(args)
  File "/home/ucbtmog/.pyenv/versions/3.5.3/lib/python3.5/site-packages/gemBS/production.py", line 367, in run
    self.do_mapping(fl)
  File "/home/ucbtmog/.pyenv/versions/3.5.3/lib/python3.5/site-packages/gemBS/production.py", line 477, in do_mapping
    if m.group(5) in [None, '.gz', '.xz', 'bz2', 'z']:
IndexError: no such group
```

**Comment by heathsc** [comment]
Ah, I should have checked this more carefully.  I can’t make the change you suggest as otherwise I do not pick up the pair identifier (1 or 2) for paired end reads.  How about this change to the regex line ?

reg = re.compile("(.*){}(.*)([12])?[.](fastq|fq|fasta|fa|bam|sam)([.][^.]+)?$".format(fli, re.I))

In this way it should match both non-paired and paired reads, and the group numbering is maintained so the rest of the program logic should work.  Could you test this with your examples?

Thanks,
Simon

**Comment by heathsc** [comment]
Almost right - the match before the [12]? needs to be non-greedy otherwise we never match the pair id.  This works better:

reg = re.compile("(.*){}(.*?)([12])?[.](fastq|fq|fasta|fa|bam|sam)([.][^.]+)?$".format(fli, re.I))
