### ISSUE TITLE
about parallelization when calling and extracting

### ISSUE THREAD

**Issue by chhylp123** [heathsc/gemBS#48]
I have read the documents of GEMBS, but I am confusing about the parallelization parameters. If the contents of pipeline configuration file are: 
> >
.....
threads = 8
jobs = 3
...
> >
I guess there are 3*8=24 CPU threads when mapping, calling and extracting. Is this right?

**Comment by IsmailM** [comment]
See this part of the docs: [http://statgen.cnag.cat/GEMBS/UserGuide/_build/html/pipelineCall.html?highlight=jobs#parallelization](http://statgen.cnag.cat/GEMBS/UserGuide/_build/html/pipelineCall.html?highlight=jobs#parallelization)

It's best to change the number of threads and jobs based on the sub-command:

- `gemBS mapping` - uses the threads argument, but not the jobs argument
- `gemBS call` - uses both threads and jobs argument - but most efficient to have max 3-4 threads and rest as jobs
- `gemBS extract` - uses the jobs argument, but not the threads argument

This is the config I use:

```python
[mapping]
# there is a threads arg but no jobs arg
threads = 24

[calling]
# max 3-4 threads, rest as jobs
jobs=8
threads=3

[extract]
# there is a jobs arg but no threads arg
jobs=24
```

**Comment by chhylp123** [comment]
> See this part of the docs: http://statgen.cnag.cat/GEMBS/UserGuide/_build/html/pipelineCall.html#parallelization
> 
> It's best to change the number of threads and jobs based on the sub-command:
> 
> * `gemBS mapping` - uses the threads argument, but not the jobs argument
> * `gemBS call` - uses both threads and jobs argument - but most efficient to have max 3-4 threads and rest as jobs
> * `gemBS extract` - uses the jobs argument, but not the threads argument
> 
> This is the config I use:
> 
> ```python
> [mapping]
> # there is a threads arg but no jobs arg
> threads = 24
> 
> [calling]
> # max 3-4 threads, rest as jobs
> jobs=8
> threads=3
> 
> [extract]
> # there is a jobs arg but no threads arg
> jobs=24
> ```

Thank you very much. 

When calling, a strange problem existed. At the first time, I have ran gemBS call sucessfully, but then it could not ran sucessfully. At the second time, gemBS call reported: 
```
: Command call started at 2019-03-17 13:57:23.190038
:
: ----------- Methylation Calling --------
: Reference       : /home/nhpcc502/ssd/gemBS_reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa
: Species         : Homo_sapiens
: Right Trim      : 0
: Left Trim       : 5
: Chromosomes     : ['KI270363.1', 'KI270579.1', 'Y', 'GL000214.1', 'KI270395.1', 'KI270734.1', 'KI270393.1', 'KI270334.1', 'KI270372.1', 'KI270509.1', 'KI270711.1', 'KI270418.1', 'KI270394.1', 'KI270315.1', 'KI270755.1', '4', 'KI270590.1', 'KI270310.1', 'KI270739.1', 'KI270312.1', 'KI270336.1', 'KI270743.1', 'KI270366.1', 'KI270382.1', 'KI270529.1', 'KI270744.1', 'KI270333.1', '15', '8', 'KI270708.1', 'KI270709.1', 'KI270583.1', 'KI270756.1', 'KI270322.1', 'KI270396.1', 'KI270580.1', 'KI270582.1', 'KI270731.1', 'KI270757.1', 'KI270387.1', 'KI270517.1', 'KI270725.1', '11', 'KI270522.1', 'GL000220.1', '1', 'KI270386.1', 'KI270515.1', 'KI270468.1', 'KI270303.1', 'KI270384.1', 'KI270420.1', 'KI270391.1', 'KI270435.1', 'KI270745.1', '12', 'KI270713.1', 'KI270392.1', 'GL000208.1', 'KI270588.1', 'KI270412.1', 'KI270728.1', 'KI270732.1', 'KI270417.1', 'KI270736.1', 'KI270305.1', 'GL000221.1', 'GL000195.1', '10', 'KI270507.1', 'GL000218.1', 'KI270376.1', 'KI270389.1', 'KI270316.1', 'KI270311.1', '22', 'KI270388.1', 'GL000216.2', 'KI270337.1', 'KI270371.1', 'KI270320.1', 'KI270751.1', 'KI270465.1', 'KI270340.1', 'KI270740.1', 'KI270742.1', 'KI270710.1', 'KI270390.1', 'KI270719.1', '7', 'KI270424.1', '19', 'GL000224.1', '20', '16', 'KI270379.1', 'KI270741.1', 'KI270720.1', 'KI270425.1', 'KI270467.1', 'KI270516.1', 'KI270729.1', 'KI270716.1', 'KI270589.1', '14', 'KI270317.1', '5', 'KI270438.1', 'KI270715.1', 'GL000213.1', 'KI270712.1', 'KI270330.1', 'KI270528.1', 'GL000194.1', 'GL000219.1', 'KI270733.1', 'KI270539.1', 'KI270544.1', 'X', 'KI270735.1', 'KI270750.1', 'KI270422.1', 'KI270508.1', 'KI270423.1', 'KI270373.1', 'KI270329.1', '9', 'KI270411.1', '13', 'KI270364.1', 'GL000008.2', 'KI270727.1', 'KI270587.1', 'KI270335.1', 'KI270511.1', 'KI270593.1', 'KI270753.1', '3', 'KI270466.1', 'KI270448.1', 'KI270747.1', 'KI270375.1', 'KI270374.1', 'KI270752.1', 'KI270383.1', 'KI270519.1', 'KI270707.1', 'KI270748.1', 'KI270385.1', 'KI270521.1', '17', 'MT', '18', '2', 'KI270304.1', 'KI270510.1', 'KI270584.1', 'KI270381.1', 'KI270726.1', '21', 'KI270512.1', 'KI270723.1', 'KI270362.1', 'KI270530.1', 'KI270706.1', 'KI270718.1', 'GL000226.1', 'KI270302.1', 'KI270714.1', 'KI270722.1', 'KI270724.1', 'KI270746.1', 'KI270730.1', 'KI270581.1', 'KI270721.1', 'KI270429.1', 'GL000225.1', 'GL000205.2', 'KI270749.1', 'KI270442.1', 'KI270738.1', 'KI270378.1', 'KI270414.1', 'KI270548.1', 'KI270518.1', 'GL000009.2', 'KI270717.1', 'KI270754.1', 'KI270591.1', 'KI270538.1', 'KI270737.1', 'KI270419.1', '6', 'KI270338.1']
: Threads         : 24
:
: Methylation Calling...
```
And it directly terminated. I tried to delete all BCF files, but gemBS call was still unable to work.

Another problem is that when I typed:
```
gemBS call -j 7 -t 4 -g 0 -f 0
```
It still reported "Left Trim       : 5". May I ask how can I make left_trim=0?

Could you help me to solve these two problems? Thank you in advance.

**Comment by heathsc** [comment]
To tackle the last problem first: --left-trim 0 being ignore was a bug where specifying some options with zero as the argument would cause them to be ignored (--left-trim 1 worked but --left-trim 0 didn’t).  A fix has been applied and pushed to github.  Thank you for the report.

For the first problem, the short answer is to run gemBS db-sync after deleting the old bcf files.  The long answer is that by default gemBS uses an on-disk database to keep track of the state of the analysis.  This allows gemBS to be used in, for example, a computer cluster where multiple independent nodes can be working on the same dataset, and prevents multiple gemBS instances from working on the same jobs at the same time.  The downside of this is that if you want to re-run a job (with different parameters for example), you must first delete the output files and then tell gemBS to synchronize the database to the current state of the filesystem (using gemBS db-sync).

Simon
