### ISSUE TITLE
problem in compilation

### ISSUE THREAD

**Issue by lmanchon** [heathsc/gemBS#5]
--Hi,

i have made some changes in my Makefile.mk.in due to some problems in compilation:
the error is due to the fact that some compilers don't accept the -Ofast option. I have changed it to a more general -O2 option, also i have removed '-march=native  -std=c99 -Wall' parameters and it  work for now.

best,
Laurent --

**Comment by heathsc** [comment]
Thank you for your suggestion.  The default optimization level has now been set to -O3.
