### ISSUE TITLE
gemBS extract does not produce bedmethyl or snps output files

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#50]
With the latest version of gemBS, gemBS extract only produces the gemBS output (even if not set). Moreover, it does not produce the ENCODE style output files or the SNP extraction files...

This is the relevant part of my config

```
[extract]
# there is a jobs arg but no threads arg
jobs=70
# strand_specific = True
phred_threshold = 10
# make_cpg = True
# make_non_cpg = True
make_bedmethyl = True
# make_bigwig = True
make_snps = True
```

And my `./.gemBS/gemBS.json`:

```json
    "extract": {
      "make_snps": "True",
      "phred_threshold": "10",
      "make_bedmethyl": "True",
      "jobs": "70"
    },
```

**Comment by heathsc** [comment]
If you change Line 189 in gemBS/__init__.py from:

 if arg != None:

to

 if arg:

Does this fix the behaviour ?

Simon

**Comment by IsmailM** [comment]
Yes - that fixes the issue for me.

Thanks,
Ismail Moghul

**Comment by heathsc** [comment]
OK, I will make the change.  Thanks for the report.

Simon

**Comment by heathsc** [comment]
Patch pushed to github
