### ISSUE TITLE
error while loading shared libraries: libmysqlclient.so.18

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#51]
I'm getting the following error running `gemBS extract`:

```bash

2019-03-27 15:15:48,683 ERROR: Process '/home/ucbtmog/.pyenv/versions/3.5.3/lib/python3.5/site-packages/gemBS/gemBSbinaries/bedToBigBed' finished with 127
2019-03-27 15:15:48,684 ERROR: /home/ucbtmog/.pyenv/versions/3.5.3/lib/python3.5/site-packages/gemBS/gemBSbinaries/bedToBigBed: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory
Exception in thread Thread-23:
Traceback (most recent call last):
ValueError: Error while making bigBed files.
```

bedToBigBed seems to be unable to see libmysqlclient.so.18...

This is despite the fact that Libmysqlclient.so.18 is available on my system at this location: `/usr/lib64/mysql/libmysqlclient.so.18`

Would appreciate any thoughts you may have in fixing this? I have reinstalled the latest version of gemBS, but that did not fix the issue...

**Comment by heathsc** [comment]
That’s annoying.  I’ve switched to building wigToBigWig and bedToBigBed from source as the latest precompiled binaries give problems with older versions of linux.  Looking at the makefile it should be linking statically unless it cannot find libmysqlclient.a.  If the precompiled binaries work for you from the UCSC site then you could try downloading them and putting them in tools/bin/ and re-running install (or copying them from an earlier version).  I will have to see how to get around this (possibly by building mysqlclient as well, but I would prefer to avoid this).  What system are you running on?

Simon

**Comment by heathsc** [comment]
Have you tried setting LD_LIBRARY_PATH to include /usr/lib64/mysql/, or ldconfig if you’re on linux?

**Comment by IsmailM** [comment]
Thanks, I will give that a go. 

I'm using Redhat, and I seem to have `libmysqlclient.a`

```bash
$ ls /usr/lib64/mysql
libmysqlclient.a
libmysqlclient_r.a
libmysqlclient_r.so
libmysqlclient_r.so.18
libmysqlclient_r.so.18.1.0
libmysqlclient.so
libmysqlclient.so.18
libmysqlclient.so.18.1.0
libmysqlservices.a
plugin
```

**Comment by IsmailM** [comment]
No, I haven't tried LD_LIBRARY_PATH - Should I set that before the python setup.py install ?

**Comment by heathsc** [comment]
No, I would try it before running gemBS.  If you try running the wigToBigWig binary directly do you get the same error?

**Comment by heathsc** [comment]
What do you get if you type   mysql_config --libs ?

**Comment by IsmailM** [comment]
That's probably the issue.

```bash

$ mysql_config --libs
-L/data/IsmailM/.progz/miniconda3/lib -lmysqlclient -lpthread -lm -lrt -ldl

$ which mysql
/usr/bin/mysql

$ which mysql_config 
/data/IsmailM/.progz/miniconda3/bin/mysql_config

```

I can remove the miniconda mysql installation (which I don't use) and retry...

**Comment by IsmailM** [comment]
This only thing that worked for me was replacing the gemBS `bedToBigBed` with a soft link to a pre-installed `bedToBigBed`...



Thanks for all your help here!
Ismail Moghul
