### ISSUE TITLE
gemBS map error

### ISSUE THREAD

**Issue by berguner** [heathsc/gemBS#52]
Hello,

I installed the gemBS from the current master branch. I am getting the following error during the mapping stage:
```
: ------------ Mapping Parameters ------------
: Sample barcode   : A001XS1
: Data set         : sample1_data_a
: No. threads      : 8
: Index            : indexes/sacCer3.BS.gem
: Paired           : True
: Read non stranded: False
: Type             : PAIRED
: Input Files      : ./fastq/sample1/sample1_data_a_1.fastq.gz,./fastq/sample1/sample1_data_a_2.fastq.gz
: Output dir       : ./mapping/A001XS1
:
: Bisulfite Mapping...
2019-04-10 16:43:12,782 ERROR: Process '/scratch/users/berguener/pyvirtual/gembs/lib/python3.6/site-packages/gemBS/gemBSbinaries/gem-mapper' finished with 1
2019-04-10 16:43:12,783 ERROR: 2019/4/10 16:43:12 -- [Opening input file './fastq/sample1/sample1_data_a_1.fastq.gz']
2019-04-10 16:43:12,783 ERROR: 2019/4/10 16:43:12 -- [Opening input file './fastq/sample1/sample1_data_a_2.fastq.gz']
2019-04-10 16:43:12,783 ERROR: 2019/4/10 16:43:12 -- [Outputting to stdout]
2019-04-10 16:43:12,783 ERROR: 2019/4/10 16:43:12 -- [Loading GEM index 'indexes/sacCer3.BS.gem']
2019-04-10 16:43:12,783 ERROR: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019-04-10 16:43:12,783 ERROR: >> GEM.System.Error::Signal raised (no=11) [errno=0,Success]
2019-04-10 16:43:12,783 ERROR: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
ValueError: Error while executing the Bisulfite bisulphite-mapping
```
I got the same error while running it for another in-house dataset.

I tried running the gem3-mapper with only index and fastq files and still got the same error. Unfortunately I could not generate a more verbose error message.

**Comment by heathsc** [comment]
This is not good...  I will look at this straight away.

Simon

**Comment by heathsc** [comment]
I can not replicate this crash on a new clean install.  Can you confirm that this problem occurs with a clean install from the current master?  Can you provide some details of your system?

Thanks,
Simon

**Comment by berguner** [comment]
I installed the pipeline in a new clean python virtual environment. I used gsl/1.16 and here are some release information of the linux:
```Cluster Manager v7.3
slave
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Scientific Linux release 6.5 (Carbon)
Scientific Linux release 6.5 (Carbon)```
I hope this helps,
Best, Bekir

**Comment by heathsc** [comment]
Did the gemBS directory already exist or did you do a fresh git clone from github?

Simon

**Comment by berguner** [comment]
I deleted the old one and I did a fresh clone.

Bekir

**Comment by heathsc** [comment]
Could you go into the tools/gem3-mapper directory and do a;  make clean && make debug

Then try and run the mapper directly from gemBS/tools/gem3-mapper/bin/gem-mapper with the index and input files.  This should provide more information about where the crash is happening.

Simon

**Comment by berguner** [comment]
I have done that ran:
`gem-mapper -I ../../indexes/sacCer3.BS.gem -1 sample1_data_a_1.fastq.gz -2 sample1_data_a_2.fastq.gz`
 and recorded the stdout and stderr. stdout didn't have anything but you can find the first 100k lines of the stderr in the attachment:
[sample1.gem3-mapper.err.gz](https://github.com/heathsc/gemBS/files/3064698/sample1.gem3-mapper.err.gz)

Bekir

**Comment by berguner** [comment]
Here are some details about the shared objects used compiling the gem3-mapper. Hope this helps.
```
ldd /scratch/users/berguener/bin/gemBS/tools/gem3-mapper/bin/gem-mapper
        linux-vdso.so.1 =>  (0x00002aaaaaaab000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00000037cbc00000)
        libm.so.6 => /lib64/libm.so.6 (0x00000037cc400000)
        librt.so.1 => /lib64/librt.so.1 (0x00000037ccc00000)
        libz.so.1 => /scratch/lab_bsf/modules/applications/zlib/1.2.11/lib/libz.so.1 (0x00002aaaaaacd000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00000037dd400000)
        libgomp.so.1 => /cm/local/apps/gcc/6.1.0/lib64/libgomp.so.1 (0x00002aaaaace8000)
        libc.so.6 => /lib64/libc.so.6 (0x00000037cb800000)
        /lib64/ld-linux-x86-64.so.2 (0x00000037cb400000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00000037cc000000)
```

Bekir

**Comment by heathsc** [comment]
Sorry for the delay.  It’s going to be difficult to track this down unless I can manage to reproduce the error!  Could you try the same run as below but turning off multi-threading (-t 1) and sending me the last 10k lines from stderr?

Thanks,
Simon

**Comment by berguner** [comment]
Here is the last 10k lines or the stderr:
[test.err.gz](https://github.com/heathsc/gemBS/files/3073200/test.err.gz)

Cheers,
Bekir

**Comment by heathsc** [comment]
Thank you, but unfortunately this does not make things any clearer.  What machine / OS are you running on?  

Simon

**Comment by berguner** [comment]
We are running Scientific Linux 6 on our machines. Our nodes are mostly made up of commodity hardware with Intel Xeon CPUs. Here is the the `uname -a` output:
```
Linux n002 2.6.32-431.20.3.el6.x86_64 #1 SMP Thu Jun 19 14:01:59 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Bekir

**Comment by heathsc** [comment]
I’ll see if I can make a static binary of the mapper that you can test.

Simon

**Comment by heathsc** [comment]
Hi Bekir,

I have a dynamically linked binary (having trouble making a static binary for the moment), but the library version numbers are  the same as yours so hopefully it should run:

https://drive.google.com/open?id=1ynnPCXk9MSj8ieiFAGzsnqwRnq-etivz <https://drive.google.com/open?id=1ynnPCXk9MSj8ieiFAGzsnqwRnq-etivz>

Can you download it and see if it runs and if it gives the same problem?

Simon

**Comment by berguner** [comment]
Hello Simon,

Yes, this binary is working. Do you need further info?

Bekir

**Comment by heathsc** [comment]
This is very odd.  So the binary I sent works correctly?  I would like to track down what is happening.  The only thing I can suggest is the following:

In tools/gem3-mapper/include/system/commons.h change line 72 to:

#define GEM_DEEP_DEBUG false

then from tools/gem3-mapper type:

make clean && make debug

and then send me the gem-mapper binary.  In principle it should run on my machine and I can see if I can replicate the crash.

Simon

**Comment by berguner** [comment]
Yes, it ran just fine and the bam files were also OK.
Here is the binary that I made with `GEM_DEEP_DEBUG false`:
[gem-mapper](https://drive.google.com/open?id=1GWGMZ4iVBOxPzVtSCeRZEZn1fIm5_5GZ)

Bekir

**Comment by heathsc** [comment]
And your binary runs without error on my machine (Linux login2.cnag 2.6.32-696.13.2.el6.Bull.128.x86_64 #1 SMP Tue Oct 10 01:42:23 CEST 2017 x86_64 GNU/Linux) on the test dataset.  I will continue to look for possible sources of the problem, but for now you have a working binary.  Please let me know if you encounter any problems with gem-mapper on other datasets.

Simon

**Comment by berguner** [comment]
Well that is weird...

I ran the pipeline on some mouse samples and it seems like the binary that you provided worked without a problem. So, thank you for the quick fix. I will keep you posted in case I encounter other problems.

Best,
Bekir
