### ISSUE TITLE
Reference file 'path/to/file' does not exist

### ISSUE THREAD

**Issue by paulstretenowich** [heathsc/gemBS#64]
Hi @heathsc,
I'm trying to use GemBS on the McGill samples and I can't specify a custom reference. I have the error `Reference file 'path/to/file' does not exist` raising at the prepare step.
My file exists at the right path, I checked with `ls` and opening a python shell doing `os.path.exists("path/to/file")` as it's done inside GemBS script. Do you have any idea about what's going on?

**Comment by heathsc** [comment]
Hi Paul,

Thanks for the report.  Could you send me your configuration files and the
output of:

GemBS --loglevel debug prepare

?

Thanks
Simon

**Comment by paulstretenowich** [comment]
Thanks for the quick reply, Here are the 2 config files and the output of the pipeline.

[prepare.log](https://github.com/heathsc/gemBS/files/3756135/prepare.log)
[IHECRE00000866.3_methylseq.txt](https://github.com/heathsc/gemBS/files/3756141/IHECRE00000866.3_methylseq.txt)
[metadata.IHECRE00000866.3_methylseq.txt](https://github.com/heathsc/gemBS/files/3756153/metadata.IHECRE00000866.3_methylseq.txt)

**Comment by heathsc** [comment]
Hi Paul,

Can you verify that the user account under which gemBS is running has permission to access the file?  os.path.exists() can also return false if the user does not have the appropriate permissions on any of the directories in the path.

Simon

**Comment by paulstretenowich** [comment]
Hi Simon,
I just found the issue. As I'm using the container, the path GemBS was looking for was not mounted inside the container so I added the -B option at the run of the container.
Thanks for the help.
Paul
