### ISSUE TITLE
gemBS extract bed file has incorrect delimiters

### ISSUE THREAD

**Issue by p-sud** [heathsc/gemBS#69]
In recent updates to the code it looks like the gemBS style bed files have an extra space inserted as a delimiter after the third column after the feature end coordinate, in addition to the usual tab. Oddly, this doesn't seem to occur with the ENCODE-style bed files. tabix also seemed to run successfully on the file too. The data here was produced by running a subset of the test set from here: http://statgen.cnag.cat/GEMBS/UserGuide/_build/html/example.html

ENCODE-style bed files:
```
> head -n 10 sample_sample5_cpg.bed | tr '  '  '#'
track#name="sample5"#description="sample5"#visibility=2#itemRgb="On"
chrI	144	145	"sample5"	0	+	144	145	0,255,0	0	0	CG	CG	80
chrI	145	146	"sample5"	27	-	145	146	0,255,0	27	0	CG	CG	2
chrI	175	176	"sample5"	0	+	175	176	0,255,0	0	0	CG	CG	107
chrI	176	177	"sample5"	39	-	176	177	0,255,0	39	0	CG	CG	2
chrI	216	217	"sample5"	0	+	216	217	0,255,0	0	0	CG	CG	107
chrI	217	218	"sample5"	36	-	217	218	0,255,0	36	0	CG	CG	2
chrI	325	326	"sample5"	0	+	325	326	0,255,0	0	0	CG	CG	80
chrI	326	327	"sample5"	28	-	326	327	0,255,0	28	0	CG	CG	2
chrI	339	340	"sample5"	1	+	339	340	0,255,0	1	0	CG	CG	73
```

gemBS-style bed file, note the `#` after the feature stop coordinate:
```
> head -n 10 sample_sample5_cpg.txt | tr  '  '  '#'
Contig	Pos0	Pos1	Ref	sample_sample5:Call	sample_sample5:Flags	sample_sample5:Meth	sample_sample5:non_conv	sample_sample5:conv	sample_sample5:support_call	sample_sample5:total
chrI	834	835#	C	C	GQ=72;MQ=60	0.000	0	4	39	40
chrI	835	836#	G	G	GQ=13;MQ=60	0.019	1	35	40	40
chrI	868	869#	C	C	GQ=81;MQ=60	0.000	0	4	31	31
chrI	869	870#	G	G	GQ=12;MQ=60	0.000	0	28	32	32
chrI	890	891#	C	C	GQ=87;MQ=60	0.000	0	4	33	33
chrI	891	892#	G	G	GQ=13;MQ=60	0.026	1	28	33	33
chrI	936	937#	C	C	GQ=123;MQ=60	0.344	1	2	44	44
chrI	937	938#	G	G	GQ=10;MQ=60	0.197	8	33	44	44
chrI	955	956#	C	C	GQ=118;MQ=60	0.699	2	1	42	42
```

I have some downstream processing that relies on the bed files being well-formed, and would appreciate a solution.

Thanks, 

Paul

**Comment by p-sud** [comment]
I should add, this is using the most current gemBS revision.

**Comment by heathsc** [comment]
Hi Paul,

Thanks for the report - clearly a bug.  Is this from the master or devel
branch?

Cheers,
Simon

**Comment by p-sud** [comment]
Thanks for the quick response Simon. This is on master

**Comment by heathsc** [comment]
OK, in the file gemBS/tools/gemBS_plugins/output.c, line 133 is currently:

fprintf(fp,"%s\t%" PRId64 "\t%" PRId64 " \t%c", args->hdr->id
[BCF_DT_CTG][rec->rid].key, rec->pos + pos, rec->pos + pos + 1, cx_len >= 3
+ pos ? cx[2 + pos] : '.');

 and should be changed to:

fprintf(fp,"%s\t%" PRId64 "\t%" PRId64 "\t%c", args->hdr->id
[BCF_DT_CTG][rec->rid].key, rec->pos + pos, rec->pos + pos + 1, cx_len >= 3
+ pos ? cx[2 + pos] : '.');

If this solves your issue then I will push the fix to master.

Thanks again for the report.
Simon

**Comment by heathsc** [comment]
I have just pushed the fix to master (and devel as the same fault was there
as well)

**Comment by p-sud** [comment]
Thanks Simon, the fix on master worked.
