### ISSUE TITLE
gemBS mapping does not limit number of threads

### ISSUE THREAD

**Issue by berguner** [heathsc/gemBS#7]
Hello,

I tried running `gemBS mapping` command with various number of threads setting the `-t` argument but `gem-mapper` always used all the cores in the computing node. Can you please check this issue?

Best,
Bekir

**Comment by MarcosFernandez** [comment]
Hi Bekir,

Thanks a lot for reporting this issue. It has been already fixed and pushed to the github repository.

Cheers,
Marcos.

**Comment by berguner** [comment]
Thanks Marcos,
Bekir
