### ISSUE TITLE
wigToBigWig error during extract

### ISSUE THREAD

**Issue by p-sud** [heathsc/gemBS#70]
Hi Simon,

I got an error with wigToBigWig running `gemBS extract`, I am using the master branch, commit 7256070f8ed0b01dfd53601f40fa05d7497df542 . I have seen this error in older versions, but it got fixed in this commit (fixed missing wig header error): https://github.com/heathsc/gemBS/commit/d1f917426bcc1e804cf808edb4d51782e9eaff46

I'm wondering it's the same issue that's back again or if it is something else, any help would be appreciated. Below is the log:

```
:
: Command extract started at 2020-02-04 17:15:45.518466
:
: Methylation Extraction...
2020-02-04 18:33:14,398 ERROR: Process '/root/.local/lib/python3.7/site-packages/gemBS/gemBSbinaries/wigToBigWig' finished with -9
ValueError: Error while extracting methylation calls.
```

Thanks,

Paul

**Comment by heathsc** [comment]
Hi Paul,

Sorry for the late reply.  Unfortunately the error message is quite generic
and just says that the wigToBigWig process failed for some reason.  This
program can often take very large amounts of memory (i.e., >64GB for human
WGBS), so this might be a reason.  Would it be possible for you to try the
devel branch?  The extract code has been totally rewritten and no longer
uses wigToBigWig or bedToBigBed to generate the bigWig and bigBed files,
and I find for a human WGBS dataset I can extract all files in parallel for
1 sample using ~6GB RAM.

Simon

**Comment by p-sud** [comment]
Hi Simon,

Thanks for the reply. The memory issue makes sense, I'm trying to run a pretty large dataset, and I was only giving extract 32 GB RAM. I'll give it a shot with more RAM, and failing that I'll give the dev branch a shot. The reduction in dependencies for the devel branch definitely makes it worth the update at some point, it's easier to just try upping the resources for now.

**Comment by p-sud** [comment]
Adding more RAM (96 GB total) worked.
