### ISSUE TITLE
gemBS index failure: bgzip not found

### ISSUE THREAD

**Issue by p-sud** [heathsc/gemBS#73]
We are trying to upgrade our version of `gemBS` to 8b33580390dd0f975dbb0f7e3f72ed34ce7b17c1 (v 3.5.0), and are getting an error about `bgzip` not found when trying to make to create the `gemBS` index:
```
FileNotFoundError: [Errno 2] No such file or directory: 'bgzip': 'bgzip'
```

In the previous version of `gemBS` we were using (this commit: 7256070f8ed0b01dfd53601f40fa05d7497df542), we did not have this issue. If I compare the Docker containers, in the old version I can find the `bgzip` in the following folder:
```
root@9b7b16e0d597:/software# ls /root/.local/lib/python3.7/site-packages/gemBS/bin
bcftools  bgzip  htsfile  samtools  tabix
```

Whereas with the new `gemBS` I can't find it there, which could explain the error:
```
root@5f64f63fce99:/software# ls /root/.local/lib/python3.7/site-packages/gemBS/bin
bcftools  samtools
```

Is there some other directory that I need to add to `PATH`? Or some other installation I need to do in the Dockerfile? Apologies if I am missing something. You can see the Docker build output here if need be: https://circleci.com/gh/ENCODE-DCC/wgbs-pipeline/760.

I can see `bgzip` as well as the other two now missing binaries `tabix` and `htsfile` all being compiled successfully in there, so maybe it is just an issue of copying them over to the Python site-packages?

Thanks,

Paul

**Comment by heathsc** [comment]
Hi Paul,

Ah got it.  I moved the htslib build directory but didn't update the
installation script.  I will update it on the site, but if you want you can
just change line 114 of setup.py from:

        for htslib in glob.glob("tools/samtools/htslib*"):

to:

        for htslib in glob.glob("tools/htslib"):

Simon

**Comment by p-sud** [comment]
Thanks Simon. I updated our Dockerfile to use the new commit you pushed and the index completes successfully now.

**Comment by heathsc** [comment]
Thanks for the report - I had had one other report of that bug but I hadn't
tracked down the problem!
