### ISSUE TITLE
R1 and R2 specific left and right trim values

### ISSUE THREAD

**Issue by will-NYGC** [heathsc/gemBS#77]
Is there a way to apply different (left|right)_trim values to R1 and R2?

**Comment by heathsc** [comment]
Not at the moment although this could be added without too much
difficulty.  For my curiosity, could you give a brief description of a
situation where this would be useful?

Cheers,
Simon

**Comment by will-NYGC** [comment]
We are using the Swift Accel-NGS MethylSeq kit on cfDNA (short frags) which appends a synthetic oligo to the 3' end of ssDNA in order to ligate adapters (https://swiftbiosci.com/wp-content/uploads/2019/02/16-0853-Tail-Trim-Final-442019.pdf). This synthetic oligo appears at the end of R1 and beginnig of R2. Rather than hardclipping the reads, we thought we could avoid defects in methylation calling caused by this by using gemBS trim values. Currently we use bwameth+MethylDackel where this is possible but we like your full gemBS pipeline and would like to switch over.

**Comment by heathsc** [comment]
OK, let me think about the best way to implement this.

Simon

**Comment by heathsc** [comment]
This has now been added in 3.5.3. From gemBS or bs_call, left_trim and right_trim options can now take either 1 or 2 values.  If 2 values are specified then this give the trim values for read 1 and read 2 respectively.  If only 1 value is specified then both reads are trimmed using the same value for the trim parameter (i.e., the previous behaviour)
