### ISSUE TITLE
gemBS merging-sample doe not with multiple threads

### ISSUE THREAD

**Issue by berguner** [heathsc/gemBS#8]
Hello,

The `gemBS sample-merging` command does not use `-t` option for setting the number of threads. It runs single threaded even if the `-t` option was set to higher values. Can you please check this issue?

Best,
Bekir

**Comment by MarcosFernandez** [comment]
Hello Bekir,

Thanks a lot for reporting this issue. It was already solved, get the last code of the repository to have the fixed version.

Cheers,
Marcos.
