### ISSUE TITLE
Logging error on call

### ISSUE THREAD

**Issue by wynstep** [heathsc/gemBS#80]
`: 
: Command call started at 2020-11-05 19:19:25.135155
: 
: ----------- Methylation Calling --------
: Reference       : /home/regmspi/Documents/ToTEM_singularity/ToTEM//src/ucsc.hg19.gemBS.ref
: Species         : Homo sapiens
--- Logging error ---
Traceback (most recent call last):
TypeError: %i format: a number is required, not str
Call stack:
Message: 'Right Trim      : %i'
Arguments: ('0',)
--- Logging error ---
Traceback (most recent call last):
TypeError: %i format: a number is required, not str
Call stack:
Message: 'Left Trim       : %i'
Arguments: ('0',)`

Any suggestion on how to fix?

**Comment by heathsc** [comment]
Can you send the configuration file and /or the command line arguments used
for the gemBS call command?

Simon

**Comment by heathsc** [comment]
This is now fixed in 3.5.5.  Thanks for reporting it.
