### ISSUE TITLE
Conversion rate is N/A in QC

### ISSUE THREAD

**Issue by paul-sud** [heathsc/gemBS#85]
Hello,

When creating the quality control reports we are noticing for a number of datasets that the bisulfite conversion rate is `N/A` in the HTML QC. We thought it might be due to low lambda coverage but there doesn't seem to be any correlation with between the lambda read depth and this value being missing.

If you could shed any light on why this value would not be available in the QC, even given a significant number of reads mapping to it, it would be much appreciated.

Thanks,

Paul

**Comment by paul-sud** [comment]
Hi, just pinging again on this, I would appreciate any insight.

**Comment by heathsc** [comment]
Hi Paul,

Could you share the json file from the mapping and the mapping report for
one of the affected datasets?

Simon

**Comment by paul-sud** [comment]
Hi Simon,

See these files (GitHub won't let me attach HTML or JSON directly):
[mapping_qc_and_json.zip](https://github.com/heathsc/gemBS/files/7163111/mapping_qc_and_json.zip)

**Comment by heathsc** [comment]
Hi Paul,

The number of reads mapping to the under-conversion control sequence is too
low and I think that a stable estimate could not be achieved.  However,
there is clearly a big problem with the mapping as you only have ~20% of
reads mapping.  Can you give me some information about the sample and the
options that you used for the mapping step?

Thanks,
Simon

**Comment by paul-sud** [comment]
This is the sample: https://www.encodeproject.org/experiments/ENCSR542QVE/

As far as mapping options the IHEC standard conf was used, then defaults for everything else. Here is the relevant sections of the gemBS.json:
```
    "mapping": {
        "underconversion_sequence": "chrL",
        "non_stranded": "False",
        "remove_individual_bams": "True"
    },
```

Looking at other datasets with the same missing conversion rate issue it does look like have varying degrees of coverage issues, which sounds like it might explain it?

**Comment by heathsc** [comment]
You might want to just try with the non-stranded option set to "True" to
see if this has any effect on the mapping rate.

Yes the low coverage for the conversion control is most likely responsible
for the 'NA' entries, but the mapping is still much lower than I would
expect.

Simon

**Comment by paul-sud** [comment]
Thanks. Looking at the old data processed with Bismark the coverage was also very low at `3.86x`, while with gemBS it is even lower `0.61x`. I'm not familiar enough with the differences between the two to say if such a discrepancy is normal, but in either case it seems like the dataset isn't really deep enough.

If we decide to rerun we can definitely try setting non-stranded set to `True` as you suggest.
