### ISSUE TITLE
Latest version to Bioconda?

### ISSUE THREAD

**Issue by ebprideaux** [heathsc/gemBS#86]
I am having an issue (https://github.com/ENCODE-DCC/wgbs-pipeline/issues/66) running the ENCODE/wgbs-pipeline, likely due to using an old version of gemBS (3.2.0, the most recent available in bioconda).

It looks like this issue was addressed here:  https://github.com/heathsc/gemBS/issues/37, but this resolution occurred after v3.2.0 was made available in bioconda.

Are there any plans to add the most recent gemBS version to bioconda?

**Comment by JakeLehle** [comment]
Hello,

I'm also having the same issue. Can @heathsc, @karl616, or @MarcosFernandez please bump the bioconda version to the latest 3.5.5.
This would be a huge help to my research! I'm trying to use your software in an improved WGBS pipeline and if I can get it finished I can write a manuscript and cite you!

I love the software and wanna keep using it! 
Help me out, please.

P.S. I would also love to see the gemBS-rs version make it's way over to bioconda too. But I'll take just having an updated gemBS on bioconda first.

Best,
Jake Lehle

**Comment by JakeLehle** [comment]
Hey @heathsc, @karl616, @MarcosFernandez or @ebprideaux    
I've been looking into this more and I can see there is an open request for gemBS to be bumped to 3.5.0 on bioconda from 9 months ago. https://github.com/bioconda/bioconda-recipes/pull/27790
Seems that some of the auto-bump checks need review by someone with write access to the main branch on bioconda. The lint check failed for some reason and hung up the version getting bumped up.
I'm gonna look at it some more and add some comments to that bump request to see if I can get some movement on this so we can get this pushed through and close this issue out.

**Comment by JakeLehle** [comment]
Okay I think I got this figured out.
I looked over the issue and suggested a fix to the pull request on
https://github.com/bioconda/bioconda-recipes/pull/27790

On the recipes/gembs/meta.yaml file please update the 41st line from 
```
- matplotlib
```
to 
```
- matplotlib-base
```

This should fix the issue with what is holding up the package from getting bumped to the 3.5.0 version and would take 5 mins.
Please make this change as soon as you can, thanks.

**Comment by heathsc** [comment]
I'm afraid that I do not know who is responsible for the bioconda package so I can not make the change that you request.

Simon

**Comment by karl616** [comment]
Hi Simon, hi Jake,

I was involved in drafting the first version of the bioconda package (with
the help of Simon).

@jake bioconda is a community effort and, in my experience, a very
welcoming one to contribute to. You can just apply on their github page and
you should be able to push the update yourself.

Best wishes,
Karl

Den tors 6 jan. 2022 11:16Simon Heath ***@***.***> skrev:

**Comment by JakeLehle** [comment]
Hi @heathsc and @karl616 

Great, thank you so much. I didn't want to overstep and meddle with your code without contacting you first to make sure you know. If you guys don't mind, I'll work on getting the package updated on bioconda and let you know if I have any questions or updates along the way. 
But from the looks of it, what you left for me should be more than enough to finish everything off. It should mainly be minor troubleshooting with the CircleCI checks.

Best,
Jake

**Comment by karl616** [comment]
Much appreciated! For clarity, it should be mentioned that I'm not a gemBS
developer. That credit goes to Simon and his team.

Den tors 6 jan. 2022 17:32Jake Lehle ***@***.***> skrev:

**Comment by JakeLehle** [comment]
Good news the update to 3.5.0 has been pushed through! I wish I could say I figured it out, but it was almost entirely @dpryan79 sheer force of will and me bugging him with pull requests and fledgling attempts at rewriting the meta.yaml from scratch along the way. He is a gentleman and a scholar and we owe him. 

Okay, I'll check back on the anaconda repository but the new package should be available for download from the bioconda channel after it updates regularly. We can close this issue out.

**Comment by ebprideaux** [comment]
Very much appreciated!  Will be sure to cite in upcoming paper!
