### ISSUE TITLE
Dealing with overlapping reads

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#87]
Hi Simon,

We are working with data from cell-free DNA (i.e. quite small fragments). We carried out paired-end sequencing at 100bp (85bp after trimming adapters etc).

As such, there are many cases, where the forward and reverse read overlap due to the small fragments.

As such, I expect that this causes a bias in the methylation value called - as you end up with two reads covering a CpG site coming from a single DNA molecule.

Firstly, does GemBS automatically deal with this situation? If not, do you have any recommendations on the best way forward?

I have tried [BamUtil clipOverlap](https://genome.sph.umich.edu/wiki/BamUtil:_clipOverlap), but I get the following error (seemingly arising from [here](https://github.com/heathsc/bs_call/blob/ef7eb81fbf556719c5e89e979e0b740234e31a74/src/al_utils.c#L138)):

```bash
2021-11-20 18:02:50,526 ERROR: Fatal error (al_utils.c:138,trim_soft_clips)
2021-11-20 18:02:50,526 ERROR: Error in CIGAR - Illegal soft clip (0 0 84 84)
```

**Comment by IsmailM** [comment]
Just saw in the paper that bscall "collapses overlapping paired-end reads".

Can you provide further information on how this is approached? 

Does BsCall simply clip one of the overlapping reads OR is it learning (and merging) information from both overlapping reads.

**Comment by heathsc** [comment]
It merges the overlapping portion of the reads.

Simon

**Comment by IsmailM** [comment]
Thanks 👍
