### ISSUE TITLE
Error when running gemBS map

### ISSUE THREAD

**Issue by boconnell89** [heathsc/gemBS#92]
I seem to get an error when running `gemBS map`. This seems to be an issue with the included samtools package? Or else it's trying to call samtools sort on a fastq file.

Note, I'm using the conda distribution as I couldn't get gemBS or gemBS-rs to compile on my machine. 

```
gemBS map
:
: Command map started at 2022-08-01 08:57:01.156815
:
: ------------ Mapping Parameters ------------
: Sample barcode    : 220727_MB_RPA
: Data set          : MB_RPA
: No. threads       : 8
: Index             : /mnt/e/refs/mm10/mm10.BS.gem
: Paired            : True
: Read non stranded : False
: Reverse conversion: None
: Type              : PAIRED
: Input Files       : /mnt/e/sciMETv2//fastq/220727_MB_RPA.trimmed.paired.R1.fq,/mnt/e/sciMETv2//fastq/220727_MB_RPA.trimmed.paired.R2.fq
: Output dir        : /mnt/e/sciMETv2//mapping/220727_MB_RPA
:
: Bisulfite Mapping...
2022-08-01 08:57:01,588 ERROR: Process '/home/oconnelb/.local/lib/python3.8/site-packages/gemBS/bin/samtools' finished with 1
2022-08-01 08:57:01,590 ERROR: /home/oconnelb/.local/lib/python3.8/site-packages/gemBS/bin/samtools: /usr/local/lib/libcurl.so.4: no version information available (required by /home/oconnelb/.local/lib/python3.8/site-packages/gemBS/bin/samtools)
2022-08-01 08:57:01,590 ERROR: samtools sort: failed to read header from "-"
ValueError: Error while executing the Bisulfite bisulphite-mapping
```

**Comment by JakeLehle** [comment]
Hi @boconnell89 I help manage the conda distribution.
Sorry to hear you are having some issues running the pipeline. Let's see if we can't figure out why samtools is giving you a hard time.

Could you try downloading and running the example data set from this link to check and see if there isn't an issue with any of your files first.
http://statgen.cnag.cat/gemBS/v3/UserGuide/_build/html/example.html

If you still get the same error can you also send me the package versions in your conda env by activating the environment and running 
```
conda list
```

Thanks.
Jake

**Comment by boconnell89** [comment]
It turns out it was an issue with the fastq file locations.  Somehow, it passed `gemBS prepare` without throwing an error.

**Comment by JakeLehle** [comment]
Glad it got sorted out!

Best,
J
